BEGIN TRANSACTION;
CREATE TABLE collection_scope (scope_id INTEGER PRIMARY KEY,start_date TEXT NOT NULL,end_date TEXT NOT NULL,exclusions TEXT NOT NULL);
INSERT INTO collection_scope VALUES(1,'2026-01-01','2026-09-20','League matches only; exclude cups, friendlies, UEFA competitions, national-team matches and non-league events.');
CREATE TABLE competitions (competition_id INTEGER PRIMARY KEY,competition_code TEXT UNIQUE NOT NULL,competition_name TEXT NOT NULL,country TEXT NOT NULL);
INSERT INTO competitions VALUES(1,'EPL','English Premier League','England');
INSERT INTO competitions VALUES(2,'LALIGA','La Liga','Spain');
INSERT INTO competitions VALUES(3,'BUNDESLIGA','Bundesliga','Germany');
INSERT INTO competitions VALUES(4,'SERIEA','Serie A','Italy');
INSERT INTO competitions VALUES(5,'LIGUE1','Ligue 1','France');
INSERT INTO competitions VALUES(6,'KLEAGUE1','K League 1','South Korea');
INSERT INTO competitions VALUES(7,'J1','J1 League','Japan');
CREATE TABLE seasons (season_id INTEGER PRIMARY KEY,competition_id INTEGER NOT NULL,season_label TEXT NOT NULL,start_date TEXT NOT NULL,end_date TEXT);
INSERT INTO seasons VALUES(1,1,'2025/26','2025-08-01','2026-05-31');
INSERT INTO seasons VALUES(2,1,'2026/27','2026-08-01','2027-05-31');
INSERT INTO seasons VALUES(3,2,'2025/26','2025-08-01','2026-05-31');
INSERT INTO seasons VALUES(4,2,'2026/27','2026-08-01','2027-05-31');
INSERT INTO seasons VALUES(5,3,'2025/26','2025-08-01','2026-05-31');
INSERT INTO seasons VALUES(6,3,'2026/27','2026-08-01','2027-05-31');
INSERT INTO seasons VALUES(7,4,'2025/26','2025-08-01','2026-05-31');
INSERT INTO seasons VALUES(8,4,'2026/27','2026-08-01','2027-05-31');
INSERT INTO seasons VALUES(9,5,'2025/26','2025-08-01','2026-05-31');
INSERT INTO seasons VALUES(10,5,'2026/27','2025-08-01','2027-05-31');
INSERT INTO seasons VALUES(11,6,'2026','2026-02-28','2026-12-31');
INSERT INTO seasons VALUES(12,7,'2026','2026-01-01','2026-12-31');
CREATE TABLE source_registry (source_id INTEGER PRIMARY KEY,source_name TEXT NOT NULL,source_type TEXT NOT NULL,authority_level TEXT NOT NULL,url TEXT,notes TEXT);
INSERT INTO source_registry VALUES(1,'Sporttery Official API','official','primary','https://webapi.sporttery.cn','Primary source for China Sports Lottery pools/markets; hhad=让球胜平负.');
INSERT INTO source_registry VALUES(2,'Football-Data','historical_dataset','secondary','https://football-data.co.uk/downloadm.php','Historical results/statistics and bookmaker/AH fields.');
INSERT INTO source_registry VALUES(3,'K League Official Open API','official','primary','https://api.kleague.com','Official K League API; requires authKey.');
INSERT INTO source_registry VALUES(4,'K League Official Portal','official_web','primary','https://www.kleague.com','Official K League records and schedule/results portal.');
INSERT INTO source_registry VALUES(5,'FBref Schedule/Results','public_web','secondary','https://fbref.com','Public schedule/results cross-check source for league fixtures and results.');
CREATE TABLE matches (match_id TEXT PRIMARY KEY,competition_id INTEGER NOT NULL,season_id INTEGER,kickoff TEXT NOT NULL,home_team TEXT NOT NULL,away_team TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'scheduled',source_status TEXT NOT NULL DEFAULT 'pending',primary_source_id INTEGER);
CREATE TABLE results (match_id TEXT PRIMARY KEY,ht_home INTEGER,ht_away INTEGER,ft_home INTEGER,ft_away INTEGER,result_1x2 TEXT,completed_at TEXT,source_status TEXT NOT NULL DEFAULT 'pending');
CREATE TABLE sporttery_market (market_id INTEGER PRIMARY KEY AUTOINCREMENT,match_id TEXT NOT NULL,pool_code TEXT NOT NULL,handicap REAL,home_value REAL,draw_value REAL,away_value REAL,captured_at TEXT,source_status TEXT NOT NULL DEFAULT 'pending');
CREATE TABLE team_features (match_id TEXT NOT NULL,team_side TEXT NOT NULL,last3 TEXT,last5 TEXT,last10 TEXT,goals_for REAL,goals_against REAL,xg_for REAL,xg_against REAL,opponent_strength REAL,PRIMARY KEY(match_id,team_side));
CREATE TABLE schedule_intent (match_id TEXT NOT NULL,team_side TEXT NOT NULL,next_opponent TEXT,next_match_time TEXT,rest_days REAL,next_match_importance TEXT,rotation_risk REAL,motivation_adjustment REAL,PRIMARY KEY(match_id,team_side));
CREATE TABLE injuries (injury_id INTEGER PRIMARY KEY AUTOINCREMENT,match_id TEXT NOT NULL,team_side TEXT NOT NULL,player TEXT NOT NULL,status TEXT,reason TEXT,expected_return TEXT,source_status TEXT NOT NULL DEFAULT 'pending');
CREATE TABLE prediction_snapshot (prediction_id INTEGER PRIMARY KEY AUTOINCREMENT,match_id TEXT NOT NULL,snapshot_time TEXT NOT NULL,data_cutoff TEXT NOT NULL,handicap REAL,handicap_prediction TEXT,score_1 TEXT,score_2 TEXT,half_full TEXT,model_confidence REAL,notes TEXT);
CREATE TABLE review (review_id INTEGER PRIMARY KEY AUTOINCREMENT,match_id TEXT NOT NULL,prediction_id INTEGER,actual_result TEXT,handicap_actual TEXT,hit_status TEXT,error_type TEXT,error_reason TEXT,calibration_change TEXT,reviewed_at TEXT);
COMMIT;
